name:                vanilla
version:             0.1.0.0
github:              "owen-d/vanilla"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/vanilla#readme>

dependencies:
- aeson >=1.4 && <1.5
- base >=4.9.1.0 && <5
- bytestring >=0.10 && <0.11
- case-insensitive
- classy-prelude >=1.5 && <1.6
- classy-prelude-conduit >=1.5 && <1.6
- classy-prelude-yesod >=1.5 && <1.6
- conduit >=1.0 && <2.0
- containers
- data-default
- directory >=1.1 && <1.4
- fast-logger >=2.2 && <2.5
- file-embed
- foreign-store
- hjsmin >=0.1 && <0.3
- http-client-tls >=0.3 && <0.4
- http-conduit >=2.3 && <2.4
- monad-control >=0.3 && <1.1
- monad-logger >=0.3 && <0.4
- persistent >=2.9 && <2.10
- persistent-sqlite >=2.9 && <2.10
- persistent-template >=2.5 && <2.9
- safe
- shakespeare >=2.0 && <2.1
- string-conv
- template-haskell
- text >=0.11 && <2.0
- time
- unordered-containers
- vector
- wai
- wai-extra >=3.0 && <3.1
- wai-logger >=2.2 && <2.4
- warp >=3.0 && <3.3
- yaml >=0.11 && <0.12
- yesod >=1.6 && <1.7
- yesod-auth >=1.6 && <1.7
- yesod-core >=1.6 && <1.7
- yesod-form >=1.6 && <1.7
- yesod-static >=1.6 && <1.7


ghc-options:
  - -W
  - -Werror
  - -optP-Wno-nonportable-include-path

library:
  source-dirs: src
  when:
  - condition: (flag(dev)) || (flag(library-only))
    then:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O0
      cpp-options: -DDEVELOPMENT
    else:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O2

executables:
  engine:
    main:                Main.hs
    source-dirs:         app/engine
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vanilla

  site:
    main: main.hs
    source-dirs: app/site
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vanilla
    when:
    - condition: flag(library-only)
      buildable: false

tests:
  engine-test:
    main:                Main.hs
    source-dirs:         test/engine
    ghc-options:
    - -Wall
    # we don't want to warn of orphans in tests as we often adhoc impl things like QuickCheck's Arbitrary
    # and it'd be a pain to newtype wrap everything
    # These classes of bugs should be caught while compiling the lib/executables (i hope)
    - -fno-warn-orphans
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vanilla
    - generic-random
    - QuickCheck
    - quickcheck-instances
    - tasty
    - tasty-quickcheck
    - tasty-hunit

  site-test:
    main: Spec.hs
    source-dirs: test/site
    ghc-options: -Wall
    dependencies:
    - vanilla
    - hspec >=2.0.0
    - yesod-test
    - microlens

# Define flags used by "yesod devel" to make compilation faster
flags:
  library-only:
    description: Build for use with "yesod devel"
    manual: false
    default: false
  dev:
    description: Turn on development settings, like auto-reload templates.
    manual: false
    default: false
